# Routing Projects
# 1 June 2015 by Nav Appaiya

# Projects
project_index:
    path: /
    defaults: { _controller: AppBundle:Page:project }

# Projecttodo - overview
project_todo:
    path:     /todo
    defaults: { _controller: AppBundle:Todo:index }

# Projecttodo - delete
project_todo_delete:
    path:      /todo/delete/{todo}
    defaults:
        _controller: AppBundle:Todo:deleteThisTodo
        todo: 1

# Project Gists
project_gists:
    path:     /gists
    defaults: { _controller: AppBundle:Gists:index }

# Project Gists
project_woo:
    path:     /woo
    defaults: { _controller: AppBundle:Woo:index }


# Project IT-eBooks
project_ebooks:
    path: /ebooks
    defaults: { _controller: AppBundle:eBook:index }
