# Routing AppBundle
# 30 may 2015 by Nav Appaiya

# Project
project:
    resource: "@AppBundle/Resources/config/routing/project.yml"
    prefix:   /project

# Homepage
nav_index:
    path:     /
    defaults: { _controller: "AppBundle:Page:home" }

# About
nav_about:
    path: /about
    defaults: { _controller: "AppBundle:Page:about" }

# News
nav_news:
    path: /news
    defaults: { _controller: "AppBundle:Page:news" }

#Contact
nav_contact:
    path: /contact
    defaults: { _controller: "AppBundle:Page:contact" }

# Error
nav_error:
    path: /error
    defaults: { _controller: "AppBundle:Page:error" }

nav_test:
    path: /test
    defaults: { _controller: "AppBundle:Test:index" }


# Cron path (runs every 15 min)
nav_cron:
    path: /cron
    defaults: { _controller: AppBundle:Cron:index }