services:
#    nav_scraper.example:
#        class: Nav\ScraperBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

# Feedburner Service
services:
    scraper.feedburner:
        class: Nav\ScraperBundle\Controller\FeedBurner

    scraper.chuck_norris:
        class: Nav\ScraperBundle\Controller\ChuckNorris
